---
title: "R Notebook"
output: html_notebook
---

```{r Setup}
library(ggplot2)
library(zoo)
library(quantmod)
library(xts)
library(PerformanceAnalytics)
library(rugarch)
```

Getting data
```{r}
getSymbols("WIPRO.NS",from = "2011-01-01",to = "2021-03-31")
chartSeries(WIPRO.NS)
```

```{r}
stockData <- WIPRO.NS$WIPRO.NS.Close
```

Calculate Daily returns and remove null
```{r}
stockData <- na.omit(lreturn)
return <- CalculateReturns(WIPRO.NS$WIPRO.NS.Close)
return <- return[-1]
return <- na.omit(return)
```


```{r}

autoplot(return)
```
```{r}
chart.Histogram(return,
                methods = c('add.density', 'add.normal'),
                colorset = c('blue', 'green', 'red'))
```

Calculate yearly rolling volatility
```{r}
chart.RollingPerformance(R = return["2011::2020"],
                         width = 22,
                         FUN = "sd.annualized",
                         scale = 252,
                         main = "Wipro's yearly rolling volatility")
```

find lowest AIC value (Akaike)
```{r}
s1 <- ugarchspec(variance.model=list(model="sGARCH",garchOrder=c(1,1)),
                mean.model=list(armaOrder=c(0,0)),distribution.model="norm")
m1 <- ugarchfit(data = return, spec = s1)
m1
```

```{r}
s2final <-  ugarchspec(variance.model=list(model="sGARCH",garchOrder=c(1,2)),
                mean.model=list(armaOrder=c(2,2)),distribution.model="norm")
m2final <- ugarchfit(data = return, spec = s2final)

f <- ugarchforecast(fitORspec = m2final, n.ahead = 365)
plot(fitted(f))
```


```{r}
sfinal <- s1
setfixed(sfinal) <- as.list(coef(m1))



sim <- ugarchpath(spec = sfinal,
                  m.sim = 1,
                  n.sim = 1*365,
                  rseed = 16)
plot.zoo(fitted(sim))
```
Creating predictions:

```{r}
prediction_April_Wipro<- 410.10*apply(fitted(sim), 2, 'cumsum') + 410.10
matplot(prediction_April_Wipro, type = "l", lwd = 3)
```



