---
title: "Fundamental Risk Classifier"
output: html_notebook
---

```{r}
library(tidyverse)
library(caret)
library(doParallel)
library(modelsummary)
```

#load data
```{r}
riskData <- readRDS("C:/Users/J Marx/Desktop/qwerty2023-main/data/cleaned/FundamentalDataCleaned.rds")

#filter to 1/10th to save computing power 2013-08-15
# riskData <- riskData  %>% 
#   filter(date < "2015-08-15")

riskData <- riskData %>% 
  select(CURRENT.RATIO, PRICE.EARNINGS.RATIO, RETURN.ON.INVESTED.CAPITAL, TOTAL.DEBT.TO.TOTAL.ASSET, TOTAL.DEBT.TO.TOTAL.EQUITY, RETURN.ON.ASSET.RATIO, category1) %>% mutate(category1 = as.factor(category1))

riskData <- riskData[-1]

head(riskData)
colSums(is.na(riskData))

```

#setup preprocesses and create partitions
```{r}
preProcess <- c("center","scale")

i <- createDataPartition(y = riskData$category1, p = 0.8, list = FALSE)

training_set <- riskData[i,]

test_set <- riskData[-i,] #should we remove the classifying column?


```

## Use parallel computing
```{r}
registerDoParallel(cores = detectCores() - 1)
```

#train the model
```{r}
trControl <- trainControl(method = "repeatedcv",number = 5,repeats = 5)

model <- train(category1 ~ ., method='knn', data = training_set, metric='Accuracy',preProcess = preProcess, trControl=trControl)
```

#testing the model
```{r}
test_set$pred <- predict(model, test_set)

test_set$fPred <- as.factor(test_set$pred)
test_set$fTruth <- as.factor(test_set$category1)

confusionMatrix(test_set$fPred, test_set$category1)
```

#saving the model
```{r}
saveRDS(model, file="C:/Users/J Marx/Desktop/qwerty2023-main/data/models/fundamentalRiskClassifier.rds")
```

