---
title: "Historical Risk Cleaning"
output: html_notebook
---

```{r Setup}
library(tidyverse)
library(dplyr)
library(readr)
library(lubridate)
library(ggplot2)
library(factoextra)
library(caret)
```


```{r}
sNpData <- read_csv("~/Desktop/qwerty2023/data/raw/all_stocks_5yrs.csv")

sNpData <- na.omit(sNpData)
```

```{r}

sNpData$date <- ymd(sNpData$date)
head(sNpData)
```

```{r}
#filtered to reduce datapoints while testing
fData <- drop_na(sNpData) 
fData
```
Finding the average price and creating a column
```{r}
#Finding the average price and creating a column
fData <- fData %>% mutate(averagePrice = (open+close)/2)

#count number of years in the dataset to make code neater + automation

fData <- fData %>% 
  group_by(Name) %>% 
  mutate(yearAvg = (sum(averagePrice))/(365.25*5)) %>% 
  mutate(yearVolumeAvg = (sum(volume))/(365.25*5))
fData

```

Calculate the diff in average price, square the diff then sum the values
```{r}
fData <- fData %>% 
  group_by(Name) %>% 
  mutate(averagePrice = sum(((averagePrice - yearAvg)^2))) %>% 
  mutate(averageVolume = sum(((volume - yearVolumeAvg)^2)))
```
find the squared varience and standard deviation

```{r}
#varience 
fData <- fData %>% 
  group_by(Name) %>% 
  mutate(varience = (averagePrice/(365.25*5))) %>% 
  mutate(volumeVarience = (averageVolume/(365.25*5)))

fData

#calculating the standard deviation
fData <- fData %>% 
  group_by(Name) %>% 
  mutate(SD = sqrt(varience)) %>% 
  mutate(SDvolume = sqrt(volumeVarience))
fData

summary(fData$SDvolume)
```

#Historical risk
```{r}
fData2 <- fData %>%
  ungroup() %>% 
  mutate(risk1 = case_when(fData$`SD`< as.numeric(substring(summary(fData$`SD`)[2],-8)) ~ "1",
                           fData$`SD`< as.numeric(substring(summary(fData$`SD`)[4],-8))~ "2",
                           fData$`SD`>= as.numeric(substring(summary(fData$`SD`)[4],-8))~ "3")) %>% 
  
   mutate(risk2 = case_when(fData$`SDvolume`< as.numeric(substring(summary(fData$`SDvolume`)[2],-8)) ~ "1",
                           fData$`SDvolume`< as.numeric(substring(summary(fData$`SDvolume`)[4],-8))~ "2",
                           fData$`SDvolume`>= as.numeric(substring(summary(fData$`SDvolume`)[4],-8))~ "3")) %>% 
  
  mutate(risk1 = as.numeric(risk1)) %>% 
  mutate(risk2 = as.numeric(risk2)) %>% 
  
  mutate(year = year(date))

fData3 <- fData2 %>% 
  mutate(riskAvg = (risk1 + risk2)/2 ) 

fData3 <- fData3 %>% 
  mutate(riskClass = case_when(riskAvg < as.numeric(substring(summary(fData3$`riskAvg`)[2],-8)) ~ "Low",
                               riskAvg < as.numeric(substring(summary(fData3$`riskAvg`)[5],-8)) ~ "Medium",
                               riskAvg >= as.numeric(substring(summary(fData3$`riskAvg`)[5],-8)) ~ "High"))
summary(fData3$riskAvg)
table(fData3$riskClass)
saveRDS(fData3,"~/Desktop/qwerty2023/data/cleaned/riskData.rds")

```

#Historical risk continued
```{r}
fData_categories <- fData2 %>% 
  select( year, Name, risk1, risk2) %>% 
  group_by(Name) %>% 
  mutate(category = (mean(c(risk1, risk2))))

fData_categories_final <- fData_categories %>% 
  summarise(mean = mean(category), .groups = 'drop')

fData_categories_final <- fData_categories_final %>% 
  mutate(historicalRisk = case_when(mean <= as.numeric(substring(summary(fData_categories_final$`mean`)[2],-8))~ "Low",
                               mean <= as.numeric(substring(summary(fData_categories_final$`mean`)[5],-8)) ~ "Medium",
                               mean > as.numeric(substring(summary(fData_categories_final$`mean`)[5],-8)) ~ "High"))

summary(fData_categories_final)
table(fData_categories_final$historicalRisk)
fData_categories_final

saveRDS(fData_categories_final,"~/Desktop/qwerty2023/data/cleaned/HistoricalRisk.rds")
```
